# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lKvibuoBTYuYVXaCocCSN1Ykr6cz6vks
"""

!pip install streamlit
import streamlit as st
import requests
from bs4 import BeautifulSoup

st.title("Monitoring PLTS Grati 1.5 MWp")

# Masukkan URL dari Ngrok di sini
URL_NGROK = "https://a1b2-202-152-x-x.ngrok-free.app"

headers = {
    "User-Agent": "Mozilla/5.0",
    "ngrok-skip-browser-warning": "69420" # Menghindari halaman peringatan bawaan ngrok
}

@st.cache_data(ttl=30) # Refresh data setiap 30 detik
def ambil_data_plts():
    try:
        response = requests.get(URL_NGROK, headers=headers, timeout=10)
        if response.status_code == 200:
            return response.text
        else:
            return None
    except Exception as e:
        return None

html_content = ambil_data_plts()

if html_content:
    st.success("Terhubung ke Server PLTS!")
    # Parsing HTML menggunakan BeautifulSoup untuk mengambil parameter yang Anda butuhkan
    soup = BeautifulSoup(html_content, 'html.parser')

    # Tampilkan isi atau ekstrak teksnya
    st.code(soup.get_text()[:500]) # Contoh menampilkan 500 karakter pertama
else:
    st.error("Gagal terhubung. Pastikan laptop lokal dan Ngrok masih berjalan.")

!./ngrok http http://grtsurya.indonesiapower.co.id:82